// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.EntityContext.Sqlite;

#nullable disable

namespace Warehouse.EntityContext.Sqlite.Migrations
{
    [DbContext(typeof(WarehouseSqliteContext))]
    partial class WarehouseSqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Warehouse.EntityContext.Entities.BoxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PalletModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PalletId");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PalletModelId");

                    b.ToTable("Boxes", (string)null);
                });

            modelBuilder.Entity("Warehouse.EntityContext.Entities.PalletEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pallets", (string)null);
                });

            modelBuilder.Entity("Warehouse.EntityContext.Entities.BoxEntity", b =>
                {
                    b.HasOne("Warehouse.EntityContext.Entities.PalletEntity", "PalletModel")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletModelId");

                    b.Navigation("PalletModel");
                });

            modelBuilder.Entity("Warehouse.EntityContext.Entities.PalletEntity", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
